name: sticker_view
description: A Flutter plugin to rotate, resize, move, delete any text, photo or other widget.
version: 0.0.2
homepage: https://github.com/gopaldhola99/sticker_view/blob/main/example/lib/main.dart
repository: https://github.com/gopaldhola99/sticker_view

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
